### ISSUE TITLE
Using options breaks "yarn install"

### ISSUE THREAD

**Issue by detcoGmbH** [joshrlesch/fastlane-plugin-yarn#10] opened 2019-09-20 14:13 UTC
Hi,
when I try to set options ("--cache-dir /some/dir" in my case), I got an error that I should use "yarn add" to add new dependencies. However I only wanted to run "yarn install".
The reason seems to be the "--" on the generated command-line:
```yarn install -- --cache-dir /some/dir```, which tells yarn that no options follow, it is used when passing positional parameters (f.e. packagenames) starting with "--"
When I remove the "-- " in line:
https://github.com/joshrlesch/fastlane-plugin-yarn/blob/8e1c1436d8def5e72ec6196d1e739d0d60ef6b11/lib/fastlane/plugin/yarn/helper/yarn_helper.rb#L30
it works.
(This used to work before, I recently updated the plugin from 1.0 to 1.1 and yarn from 1.10 to 1.17)
Thanks

**Comment by joshrlesch** [comment] 2019-10-03 17:49
Hey @detcoGbR, mind trying out this branch to see if it works as intended. This should fix the extra `--` getting added to options. 
https://github.com/joshrlesch/fastlane-plugin-yarn/pull/12

**Comment by joshrlesch** [comment] 2019-10-23 20:15
Fixed in https://github.com/joshrlesch/fastlane-plugin-yarn/releases/tag/v1.2

**Closed as completed by joshrlesch** 2019-10-23 20:15 UTC
